# Лабораторная работа 5. Векторизация

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
train_df = pd.read_csv('./train_dataset.csv')
val_df = pd.read_csv('./val_dataset.csv')
test_df = pd.read_csv('./test_dataset.csv')

In [ ]:
train_df

id_post                      date  \
5034     4989 2020-02-11 11:27:03+00:00   
3893     6772 2021-01-14 14:37:31+00:00   
7603     1501 2017-04-30 12:51:05+00:00   
1504    10761 2023-05-23 11:45:00+00:00   
7859     1217 2017-03-14 08:44:56+00:00   
...       ...                       ...   
6136     3456 2019-02-03 11:16:07+00:00   
3183     7849 2021-08-05 10:35:25+00:00   
1069    11374 2023-11-02 14:01:37+00:00   
4041     6554 2020-12-09 05:45:04+00:00   
1628    10548 2023-04-04 12:39:33+00:00   

                                                   text  views  reactions  \
5034  **«Клавиатуры Apple просто кошмарные»**\n\nТай...  24190          0   
3893  [​​](https://telegra.ph/file/db52690d951f25b63...  19172          1   
7603  Google запустила новый курс для разработчиков....   9240          0   
1504  [​](https://telegra.ph/file/5dbe062e7dd0301078...  15515         40   
7859  Поисковик Google наконец научился обрабатывать...   2857          0   
...                                                 ...    ...        ...   
6136  **Развёрнутое руководство по Sass/SCSS**\n\nht...  24259          0   
3183  [​](http://chnly.pro/file/305a115d080a42c7a6b9...  18215          0   
1069  **Подборка актуальных вакансий**\n\n— [Специал...  13645         18   
4041  **Microsoft запатентовала рейтинг для оценки с...  18028          0   
1628  [​](http://api.channely.co/file/26f0f21e04934e...  15271         44   

      comments  hour    weekday  popularity  \
5034         0    11    Tuesday           1   
3893        24    14   Thursday           1   
7603         0    12     Sunday           0   
1504        15    11    Tuesday           0   
7859         0     8    Tuesday           0   
...        ...   ...        ...         ...   
6136         0    11     Sunday           1   
3183         4    10   Thursday           1   
1069         0    14   Thursday           0   
4041         0     5  Wednesday           1   
1628         0    12    Tuesday           0   

                                             clean_text  text_length  \
5034  клавиатура apple просто кошмарный тайка вайтит...          330   
3893  заменить участник голубой огонёк николас кейдж...          149   
7603  google запустить новый курс разработчик посвят...          111   
1504  знать код страница найти возможно ещё парочка ...          133   
7859  поисковик google научиться обрабатывать спецси...           99   
...                                                 ...          ...   
6136  развернуть руководство sassscss современный cs...          323   
3183  вопрос который точно стоить задать работодател...          351   
1069  подборка актуальный вакансия специалист технич...          701   
4041  microsoft запатентовать рейтинг оценка совещан...          465   
1628  разрабатывать starcraft starcraft культовый ст...          333   

      engagement  engagement_rate  
5034           0         0.000000  
3893          25         0.001304  
7603           0         0.000000  
1504          55         0.003545  
7859           0         0.000000  
...          ...              ...  
6136           0         0.000000  
3183           4         0.000220  
1069          18         0.001319  
4041           0         0.000000  
1628          44         0.002881  

[6321 rows x 13 columns]

### Мешок слов (Bag of Words, BoW)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(train_df['clean_text']).toarray()
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_val = vectorizer.transform(val_df['clean_text']).toarray()
X_test = vectorizer.transform(test_df['clean_text']).toarray()

In [ ]:
len(vectorizer.vocabulary_)

19275

In [ ]:
vectorizer.get_feature_names_out()[:20]

array(['aaaкласса', 'aaaокружение', 'ab', 'abap', 'abapразработчик',
       'abbyy', 'abilities', 'ability', 'abilityaware', 'about',
       'aboutcloud', 'above', 'absence', 'absolute', 'abтеста',
       'abтестирование', 'abтестированию', 'abтестирования', 'abтесты',
       'academic'], dtype=object)

In [ ]:
nonzero_indices = X_train[0].nonzero()[0]
print([vectorizer.get_feature_names_out()[i] for i in nonzero_indices])

['qa', 'бесплатный', 'большой', 'важный', 'возможность', 'грамотный', 'команда', 'материал', 'навык', 'очень', 'программист', 'прокачка', 'разработка', 'свой', 'составить', 'список', 'ссылка', 'тестирование', 'тестировщик', 'член']


In [ ]:
import joblib
#сохранение предобученных моделей sklearn
joblib.dump(vectorizer, './BoW_pretrained.joblib')

#загрузка предобученных моделей
BoW_pretrained = joblib.load('./BoW_pretrained.joblib')

In [ ]:
BoW_pretrained.transform(['aaaкласса', 'aaaокружение', 'ab']).toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [ ]:
pd.DataFrame(X_train).to_csv('./X_train_vec_BoW.csv', index=False)
pd.DataFrame(X_val).to_csv('./X_val_vec_BoW.csv', index=False)
pd.DataFrame(X_test).to_csv('./X_test_vec_BoW.csv', index=False)

### TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X_train = tfidf_vectorizer.fit_transform(train_df['clean_text']).toarray()

X_val = tfidf_vectorizer.transform(val_df['clean_text']).toarray()
X_test = tfidf_vectorizer.transform(test_df['clean_text']).toarray()

In [ ]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidf_vectorizer.get_feature_names_out()[-20:]

array(['ярославль', 'ярославский', 'ярость', 'ярый', 'ясно', 'ясный',
       'ячеекклетка', 'ячеистый', 'ячейка', 'яша', 'яшин', 'ящерица',
       'ящик', 'ёкнуть', 'ёлка', 'ёлочка', 'ёлочный', 'ёмко', 'ёмкость',
       'ёпт'], dtype=object)

In [ ]:
print(X_train.shape, X_val.shape, X_test.shape)

(4773, 19275) (843, 19275) (992, 19275)


In [ ]:
# Для сохранения и загрузки
joblib.dump(tfidf_vectorizer, './TF_IDF_pretrained.joblib')

tfidf_pretrained = joblib.load('./TF_IDF_pretrained.joblib')

In [ ]:
tfidf_pretrained.transform(['ёмко', 'ёмкость', 'ёпт']).toarray()

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
pd.DataFrame(X_train).to_csv('./X_train_vec_TF_IDF.csv', index=False)
pd.DataFrame(X_val).to_csv('./X_val_vec_TF_IDF.csv', index=False)
pd.DataFrame(X_test).to_csv('./X_test_vec_TF_IDF.csv', index=False)

### Word2Vec

In [ ]:
!pip install --upgrade numpy gensim

  Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)


In [ ]:
import nltk
from string import punctuation
from pymorphy3 import MorphAnalyzer
from gensim.models import Word2Vec
nltk.download('punkt_tab')

morph = MorphAnalyzer()
punctuations = list(punctuation)
extra_punct = ['``','...',"''",'«','»','…','”','”','“','-','–','..']
punctuations.extend(extra_punct)


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:

def prep_text(text, morph = morph, punctuations = punctuations):
    text_token = nltk.word_tokenize(text)
    text_word=[morph.parse(x.lower())[0].normal_form for x in text_token if x not in punctuations]
    return text_word

# Применяем предобработку
X_token_train = [prep_text(text) for text in train_df['clean_text']]
X_token_val = [prep_text(text) for text in val_df['clean_text']]
X_token_test = [prep_text(text) for text in test_df['clean_text']]

In [ ]:
w2v_model = Word2Vec(sentences=X_token_train, vector_size=300, window=5, min_count=1, epochs=100)

# Получаем словарь модели
vocab = list(w2v_model.wv.key_to_index)


print("Первые 10 слов словаря:", vocab[:10])
print("Размер словаря:", len(vocab))

Первые 10 слов словаря: ['который', 'год', 'это', 'работа', 'разработчик', 'новый', 'свой', 'код', 'опыт', 'дать']
Размер словаря: 22150


In [ ]:
import numpy as np
#вектора каждого слова из предложения
preprocessing_text = ['кот', 'любить', 'тыгыдыкать']
vectors_word = []
for i in preprocessing_text:
  if i in vocab:
    vectors_word.append(w2v_model.wv[list(w2v_model.wv.index_to_key)[vocab.index(i)]])
  else:
    vectors_word.append(np.zeros(300))
vector_text = np.mean(vectors_word, axis = 0)

In [ ]:
#векторизация каждого слова по отдельности
print(vectors_word)

[array([ 5.88878453e-01,  1.48376989e+00,  8.12659740e-01,  6.09058857e-01,
        1.33264315e+00,  1.95973754e+00, -3.96404624e-01,  4.79142457e-01,
        1.36182368e+00, -6.57133818e-01, -1.13861191e+00,  2.27832496e-01,
       -2.91920975e-02, -5.89934945e-01,  9.21105519e-02,  5.23980200e-01,
        8.42746496e-01, -2.58084744e-01, -8.66401941e-02, -4.28461403e-01,
        2.21642360e-01,  4.20439750e-01, -3.10777932e-01, -1.35844827e+00,
       -1.08260620e+00,  1.70453638e-02, -4.42649841e-01,  1.58733909e-03,
       -2.04477534e-01,  1.75749391e-01, -4.30602372e-01,  1.15908051e+00,
       -3.65881592e-01,  6.34654045e-01, -1.42402196e+00,  8.71070385e-01,
        8.97753954e-01,  1.24183488e+00,  4.70594257e-01, -1.09732735e+00,
        1.26351804e-01,  2.75892437e-01, -2.79087901e-01,  5.63389026e-02,
       -1.76594448e+00, -2.15559378e-01,  1.43899262e+00,  1.35999289e-03,
       -7.04726696e-01,  2.50759125e-01, -1.07959890e+00, -4.93533202e-02,
       -1.74900401e+00, 

In [ ]:
#векторизация одного текста целиком
print(vector_text)

[ 0.63508938  0.03670732  0.19413871 -0.29497488  0.01944208  0.76158027
 -0.22792623  0.32770686  1.10344823 -0.70065351 -0.61418734 -0.07428497
  0.26789482 -0.65480904  0.29744549  0.50025489  0.02763313 -0.22741213
 -0.17164577 -0.4582488   0.67444821  0.24697442 -0.78042866 -0.41482297
 -0.52932096  0.40548797 -0.42063866 -0.10511632 -0.26576389  0.18038092
 -0.25267206  0.13071092 -0.2910867   0.47670633 -0.24344979 -0.49160059
  0.43088256  0.30860973 -0.09487115 -0.9119664   0.14479665  0.43072822
  0.27552132  0.01321292  0.06497085 -0.19249102  0.12952737  0.17105841
  0.17597536 -0.23227827 -0.77370699 -0.0481905  -0.8201678   0.30910785
  0.58262433 -0.25810484 -0.92254853 -0.0589695  -0.67648985 -0.38067494
  0.49872234 -0.53190212 -0.24223884 -0.30978195 -0.67921579  0.23023008
  0.01890339  0.4130071  -0.63371774 -0.23181484 -0.22381404  0.64200314
 -0.20614766 -0.52843879 -0.64568907 -0.11502484  0.19057835 -0.69736401
  0.13935371  0.0527865   0.19786088  0.99857899 -0

In [ ]:
vocab

['который',
 'год',
 'это',
 'работа',
 'разработчик',
 'новый',
 'свой',
 'код',
 'опыт',
 'дать',
 'язык',
 'статья',
 'компания',
 'проект',
 'google',
 'разработка',
 'самый',
 'работать',
 'программирование',
 'python',
 'удалённый',
 'инструмент',
 'такой',
 'система',
 'использовать',
 'сайт',
 'программист',
 'нейросеть',
 'время',
 'другой',
 'приложение',
 'игра',
 'москва',
 'стать',
 'помощь',
 'пользователь',
 'всё',
 'технология',
 'один',
 'первый',
 'новость',
 'ещё',
 'наш',
 'задача',
 'подборка',
 'команда',
 'какой',
 'создать',
 'человек',
 'курс',
 'версия',
 'рассказывать',
 'вакансия',
 'рассказать',
 'также',
 'ия',
 'сделать',
 'мочь',
 'microsoft',
 'алгоритм',
 'обучение',
 'помочь',
 'хороший',
 'windows',
 'сервис',
 'java',
 'c',
 'собеседование',
 'день',
 'эксперт',
 'каждый',
 'получить',
 'просто',
 'нужно',
 'создание',
 'ваш',
 'вопрос',
 'безопасность',
 'видео',
 'совет',
 'пример',
 'javascript',
 'интересный',
 'знать',
 'решение',
 'несколько',

In [ ]:
import numpy as np

def text_to_vec(tokens, model, vocab):

    vector_size = 300
    vectors = []

    for word in tokens:
        if word in vocab:
            try:
                word_idx = vocab.index(word)
                model_word = model.wv.index_to_key[word_idx]
                vectors.append(model.wv[model_word])
            except (IndexError, KeyError):
                # Если индекс выходит за границы или слова нет в модели
                vectors.append(np.zeros(vector_size))
        else:
            vectors.append(np.zeros(vector_size))

    # Делаем вектор нужной размерности во избежание ошибок
    if not vectors:
        return np.zeros(vector_size)

    mean_vector = np.mean(vectors, axis=0)
    return mean_vector

X_train_vec = np.array([text_to_vec(tokens, w2v_model, vocab) for tokens in X_token_train])
X_val_vec = np.array([text_to_vec(tokens, w2v_model, vocab) for tokens in X_token_val])
X_test_vec = np.array([text_to_vec(tokens, w2v_model, vocab) for tokens in X_token_test])

In [ ]:
vocab_size = len(w2v_model.wv.key_to_index)
print(f"Количество уникальных слов в словаре: {vocab_size}")
print(w2v_model.wv.key_to_index)

Количество уникальных слов в словаре: 22150
{'который': 0, 'год': 1, 'это': 2, 'работа': 3, 'разработчик': 4, 'новый': 5, 'свой': 6, 'код': 7, 'опыт': 8, 'дать': 9, 'язык': 10, 'статья': 11, 'компания': 12, 'проект': 13, 'google': 14, 'разработка': 15, 'самый': 16, 'работать': 17, 'программирование': 18, 'python': 19, 'удалённый': 20, 'инструмент': 21, 'такой': 22, 'система': 23, 'использовать': 24, 'сайт': 25, 'программист': 26, 'нейросеть': 27, 'время': 28, 'другой': 29, 'приложение': 30, 'игра': 31, 'москва': 32, 'стать': 33, 'помощь': 34, 'пользователь': 35, 'всё': 36, 'технология': 37, 'один': 38, 'первый': 39, 'ещё': 40, 'новость': 41, 'наш': 42, 'задача': 43, 'подборка': 44, 'команда': 45, 'какой': 46, 'создать': 47, 'человек': 48, 'курс': 49, 'версия': 50, 'рассказывать': 51, 'вакансия': 52, 'рассказать': 53, 'также': 54, 'ия': 55, 'сделать': 56, 'мочь': 57, 'microsoft': 58, 'алгоритм': 59, 'обучение': 60, 'помочь': 61, 'хороший': 62, 'windows': 63, 'сервис': 64, 'java': 65, 'c

In [ ]:
#посмотреть ближайшие слова
w2v_model.wv.most_similar('разработка')

[('создание', 0.2904225289821625),
 ('автоматизация', 0.2840465307235718),
 ('разрабатывать', 0.2839258015155792),
 ('построение', 0.27270811796188354),
 ('взаимодействие', 0.25958454608917236),
 ('различие', 0.25654712319374084),
 ('вебразработка', 0.2558174431324005),
 ('реализация', 0.24713048338890076),
 ('ma', 0.24699506163597107),
 ('гринат', 0.2462143748998642)]

In [ ]:
#посмотреть косинусную близость двух слов
print(w2v_model.wv.similarity('разработка', 'google'))
print(w2v_model.wv.similarity('разработка', 'разработчик'))
print(w2v_model.wv.most_similar(positive=['разработка','разработчик'], negative=['проектирование'], topn=1))

-0.027841603
0.19744997
[('компанияразработчик', 0.33289381861686707)]


In [ ]:
w2v_model.save('./W2V_pretrained.bin')

pd.DataFrame(X_train_vec).to_csv('./X_train_vec_W2V.csv', index=False)
pd.DataFrame(X_val_vec).to_csv('./X_val_vec_W2V.csv', index=False)
pd.DataFrame(X_test_vec).to_csv('./X_test_vec_W2V.csv', index=False)